#!/usr/bin/env php
<?php

// just run if, the executed file is this file
if(realpath(__FILE__) == realpath($_SERVER['SCRIPT_FILENAME'])) {
	/*$_cfgDiff_myStat = stat(__FILE__);
	$_cfgDiff_scriptStat = stat($_SERVER['SCRIPT_FILENAME']);
	$_cfgDiff_Run = true;
	foreach(array('dev', 'ino', 'mode', 'nlink', 'uid', 'gid', 'rdev', 'size', 'ctime') as $k) {
		if(@$_cfgDiff_myStat[$k] != @$_cfgDiff_scriptStat[$k]) {
			$_cfgDiff_Run = false;
			break;
		}
	}
	if($_cfgDiff_Run) {
		startCfgDiff();
	}*/
	startCfgDiff();
}

function startCfgDiff() {
	if(php_sapi_name() !== 'cli') throw new \RuntimeException('Cannot start. This script requires cli.');

	$opts = array(
		'v' => 0,
		'color' => null,
		'stat' => true,
		'diff' => true,
		'cfgProcessors' => array(),
	);
	$args = array();
	foreach($_SERVER['argv'] as $i => $v) {
		if($i == 0) continue;
		switch($v) {
			case '-h': $opts['h'] =  true; break;
			case '-q':   $opts['v'] =  ( $opts['v'] <= 0 ? -1: max($opts['v'], -1) ); break;
			case '-v':   $opts['v'] =  max($opts['v'], 1); break;
			case '-vv':  $opts['v'] =  max($opts['v'], 2); break;
			case '-vvv': $opts['v'] =  max($opts['v'], 3); break;
			case '--stat':    $opts['stat'] = true;  break;
			case '--no-stat': $opts['stat'] = false; break;
			case '--just-stat': $opts['stat'] = true; $opts['diff'] = false; $opts['v'] =  ( $opts['v'] <= 0 ? -1: max($opts['v'], -1) ); break;
			case '--just-diff': $opts['stat'] = false; $opts['diff'] = true; $opts['v'] =  ( $opts['v'] <= 0 ? -1: max($opts['v'], -1) ); break;
			case '--color':    $opts['color'] = true;  break;
			case '--no-color': $opts['color'] = false; break;
			case '--': $i++; break(2);
			default: break(2);
		}
	}
	$args = array_slice($_SERVER['argv'], $i);

	if(count($args) < 2 || $args[0] == '' || $args[1] == '' || (isset($opts['h']) && $opts['h'])) {
		$writer = new ConsoleWriter(3, $opts['color']);
		$writer->setColor('brown');
		$writer->write("+-------------------------------------------------------+\n");
		$writer->write("| Show the difference between two Icinga configurations |\n");
		$writer->write("+-------------------------------------------------------+\n\n");
		$writer->setColor();
		$writer
			->write("USAGE: ")
			->write(basename($_SERVER['argv'][0]), 0, 'brown')
			->write(" [options] ", 0, 'green')
			->write("globpath1")
			->write(" ")
			->write("globpath2")
			->write("\n\n")
		;
		if(function_exists('echo_help_summary')) echo_help_summary();
		$writer->write("\t-h ", 0, 'green')->write("= Show this help\n");
		$writer->write("\t-q, -v, -vv, -vvv  ", 0, 'green')->write("= Set the verbosity (quiet, verbose, very verbose, debug)\n");
		$writer->write("\t--stat      ", 0, 'green')->write("= Show the statistics\n");
		$writer->write("\t--no-stat   ", 0, 'green')->write("= Don't show the statistics\n");
		$writer->write("\t--just-stat ", 0, 'green')->write("= Just show the statistics (this also sets verbosity to quiet)\n");
		$writer->write("\t--just-diff ", 0, 'green')->write("= Just show the diff (this also sets verbosity to quiet)\n");
		$writer->write("\t--no-color  ", 0, 'green')->write("= Do not use terminal colors\n");
		$writer->write("\t--color     ", 0, 'green')->write("= Use terminal colors\n");
		exit();
	}

	if($opts['v'] >= 1) echo "Reading the configuration from glob path \"" . $args[0] . "\" into memory\n";
	$cfg1 = new Cfg($args[0], $opts['v']);
	if($opts['v'] >= 1) echo "Reading the configuration from glob path \"" . $args[1] . "\" into memory\n";
	$cfg2 = new Cfg($args[1], $opts['v']);

	if($opts['stat'] == false && $opts['diff'] == false) {
		if($opts['v'] >= 1) echo "WARNING: Not calculating any diff...\n\n";
	}
	else {
		if($opts['v'] >= 1) echo "Calculating the diff...\n\n";
		$cfg1->diff($cfg2, $opts['color'])->display(
			$opts['stat'],
			$opts['diff']
		);
	}
}

class PathCompressor {
	private static $id = 0;
	private static $pathToId = array();
	private static $idToPath = array();

	public static function getId($path) {
		$path = (string)$path;
		if(!isset(self::$pathToId[$path])) {
			self::$id++;
			self::$pathToId[$path] = self::$id;
			self::$idToPath[self::$id] = $path;
		}
		return self::$pathToId[$path];
	}
	public static function getPath($id) {
		$id = (int)$id;
		if(isset(self::$idToPath[self::$id])) {
			return self::$idToPath[self::$id];
		}
		return null;
	}
}

class ClosureCfgProcessor implements CfgProcessor {
	protected $func;

	public function __construct(\Closure $func) {
		$this->func = $func;
	}

	public function processValues($definedObject, array $definedVals, $verbosity) {
		$f = $this->func;
		return $f($definedObject, $definedVals, $verbosity);
	}
}

Interface CfgProcessor {
	/**
	 * Rewrites aand/or filters object values
	 *
	 * It can be used to modify the diff by deleting or normalizing values
	 * @param string $definedObject the name of the object
	 * @param string $definedObject the name of the object
	 * @param array  $definedVals the defined values ( the actual values are under:  $definedVals['v'][KEYNAME]['v'] )
	 * @param int  $verbosity  the verbosity ( -1 = quiet, 0 = noraml, 1 = verbose, 2 = very verbose, 3 = debug)
	 * @return array  the new $definedVals or empty array in case the whole object should be ignored
	 */
	public function processValues($definedObject, array $definedVals, $verbosity);
}

class Cfg {
	protected $globpath;
	protected $parsedObjects = array();
	protected $writer;

	protected static $processors = array();

	public function __construct($globpath, $verbosity = 0) {
		$this->globpath = (string)$globpath;
		$this->verbosity = (int)$verbosity;
		$this->writer = new ConsoleWriter($verbosity, null);
		$this->update();
	}

	public function getParsedObjects() {
		return $this->parsedObjects;
	}

	public function update() {
		$this->parsedObjects = $this->getRecursiveCfgArray($this->globpath);
		return $this;
	}

	public function diff(Cfg $cfg, $useColors = null) {
		return new cfgDiff($this, $cfg, $useColors);
	}

	public static function pushProcessor(CfgProcessor $p) {
		self::$processors[] = $p;
	}
	public static function clearProcessors() {
		self::$processors[] = array();
	}

	protected function say($str, $level) {
		$this->writer->write($str, $level);
	}

	protected function processValues($definedObject, array $definedVals) {
		// is function can be used to modify the diff by deleting or normalizing values
		// IDEALLY THIS FUNCTION SHOULD JUST DO NOTHING:
		foreach(self::$processors as $p) {
			$definedVals = $p->processValues($definedObject, $definedVals, $this->verbosity);
			if(!is_array($definedVals) || empty($definedVals)) return array();
		}
		return $definedVals;
	}

	protected function getCfgKey($definedObject, array $definedVals) {
		// template
		if(isset($definedVals['v']['name']['v'])) {
			if(!isset($definedVals['v']['register']['v']) || $definedVals['v']['register']['v'] != 0) {
				$this->say("\t\tWARNING: You have a registered Template $definedObject (defined in " . PathCompressor::getPath($definedVals['p']) . ":" . $definedVals['l'] . ")\n", 0);
			}
			return 'template-' . $definedObject . '||' . $definedVals['v']['name']['v'];
		}
		switch($definedObject) {
			case 'service':
				return  $definedObject . '||' . $definedVals['v']['host_name']['v'] . '||' . $definedVals['v']['service_description']['v'];
			case 'host':
				return  $definedObject . '||' . $definedVals['v']['host_name']['v'];
			case 'servicedependency':
				return  $definedObject . '||' . $definedVals['v']['host_name']['v'] . '||' . $definedVals['v']['service_description']['v'] . '||' . $definedVals['v']['dependent_host_name']['v'] . '||' . $definedVals['v']['dependent_service_description']['v'];
			case 'timeperiod':
				return  $definedObject . '||' . $definedVals['v']['timeperiod_name']['v'];
			case 'command':
				return  $definedObject . '||' . $definedVals['v']['command_name']['v'];
			case 'contact':
				return  $definedObject . '||' . $definedVals['v']['contact_name']['v'];
			case 'hostgroup':
				return  $definedObject . '||' . $definedVals['v']['hostgroup_name']['v'];
			case 'servicegroup':
				return  $definedObject . '||' . $definedVals['v']['servicegroup_name']['v'];
			case 'contactgroup':
				return  $definedObject . '||' . $definedVals['v']['contactgroup_name']['v'];
			default:
				$this->say("\t\tERROR: Unknown Object $definedObject - using '' as key (defined in " . PathCompressor::getPath($definedVals['p']) . ":" . $definedVals['l'] . ")\n", 0);
				return '';
		}
	}

	protected function getRecursiveCfgArray($cfgpath) {
		$timeperiodKeys = array(
			'timeperiod_name' => true,
			'alias'	=> true,
			'exclude' => true
		);
		if($cfgpath[strlen($cfgpath)-1] == '/') {
			$cfgpath = substr($cfgpath, 0, -1);
		}
		$cfg = array();
		foreach(glob($cfgpath) as $p) {
			if(is_dir($p)) {
				$this->say("\tProcessing path: $p\n", 2);
				foreach(glob("$p/*") as $p) {
					// no directory && no *.cfg file? skip this entry
					if(!is_dir($p) && !fnmatch("*.cfg", $p)) continue;
					$subcfg = $this->getRecursiveCfgArray($p);
					foreach($subcfg as $definedObject => $a) {
						if(!isset($cfg[$definedObject])) {
							$cfg[$definedObject] = $a;
							continue;
						}
						foreach($a as $k => $definedVals) {
							if(!isset($cfg[$definedObject][$k])) {
								$cfg[$definedObject][$k] = $definedVals;
								continue;
							}
							$this->say("\t\tERROR: $definedObject \"$k\" has been defined twice (defined in " . PathCompressor::getPath($a[$k]['p']) . ":" . $a[$k]['l'] . " and in " . PathCompressor::getPath($cfg[$definedObject][$k]['p']) . ":" . $cfg[$definedObject][$k]['l'] . ")\n", 0);
							// $cfg[$definedObject][$k] = $definedVals; // comment the foreach loop, when using this line
							foreach($definedVals['v'] as $key => $val) { // comment the above line, when using this loop
								if(isset($cfg[$definedObject][$k]['v'][$key])) {
									$this->say("\t\tERROR: Overwriting existing value from " . PathCompressor::getPath($cfg[$definedObject][$k]['v'][$key]['p']) . ":" . $cfg[$definedObject][$k]['v'][$key]['l'] . "  with the new value from " . PathCompressor::getPath($val['p']) . ":" . $val['l']."\n", 1);
								}
								else {
									$this->say("\t\tERROR: Adding new value from " . PathCompressor::getPath($val['p']) . ":" . $val['l']." to an already defined object\n", 1);
								}

								$cfg[$definedObject][$k]['v'][$key] = $val;
							}
						}
					}
				}
			}
			else {
				$this->say("\tProcessing file: $p\n", 2);
				if($fp = fopen($p, 'r')) {
					$isInDefine = false;
					$definedObject = '';
					$definedVals = array('p' => '', 'l' => 0, 'v' => array());
					$l = 0;
					while(!feof($fp)) {
						$l++;
						$line = trim(fgets($fp, 512000));
						if($line == '' || $line[0] == '#') continue;
						//$this->say("\t\t$line\n", 3);
						if($isInDefine) {
							if($line == '}') {
								// get k to have it in case it will be ignored...
								$k = strtolower($this->getCfgKey($definedObject, $definedVals));
								// filer or rewrite  values
								$definedVals = $this->processValues($definedObject, $definedVals);
								//print_r($definedVals);
								//$this->say("End of Define: $definedObject\n", 3);
								if(empty($definedVals)) {
									$this->say("\t\tNOTICE: Ignoring the object $definedObject \"$k\"\n", 1);
								}
								else {
									// get k after rewrites or filtered values
									$k = strtolower($this->getCfgKey($definedObject, $definedVals));
									if(isset($cfg[$definedObject][$k])) {
										$this->say("\t\tERROR: $definedObject \"$k\" has been defined twice (defined in " . PathCompressor::getPath($cfg[$definedObject][$k]['p']) . ":" . $cfg[$definedObject][$k]['l'] . " and in $p:$l)\n", 0);
										// $cfg[$definedObject][$k] = $definedVals; // comment the foreach loop, when using this line
										foreach($definedVals['v'] as $key => $val) { // comment the above line, when using this loop
											if(isset($cfg[$definedObject][$k]['v'][$key])) {
												$this->say("\t\tERROR: Overwriting existing value from " . PathCompressor::getPath($cfg[$definedObject][$k]['v'][$key]['p']) . ":" . $cfg[$definedObject][$k]['v'][$key]['l'] . "  with the new value from " . PathCompressor::getPath($val['p']) . ":" . $val['l']."\n", 1);
											}
											else {
												$this->say("\t\tERROR: Adding new value from " . PathCompressor::getPath($val['p']) . ":" . $val['l']." to an already defined object\n", 1);
											}
											$cfg[$definedObject][$k]['v'][$key] = $val;
										}
									}
									else {
										$cfg[$definedObject][$k] = $definedVals;
									}
								}

								$isInDefine = false;
								$definedObject = '';
								$definedVals = array('p' => '', 'l' => 0, 'v' => array());
							}
							else {
								if(preg_match('/^(\S+)\s+(.*)$/', $line, $matches)) {
									if($definedObject == 'timeperiod' && !isset($timeperiodKeys[$matches[1]])) {
										$matches[0] = preg_replace('/\s+/', ' ', $matches[0]);
										if(isset($definedVals['v'][$matches[0]])) {
											$this->say("\t\tERROR: Value \"" . $matches[0] . "\" has been defined twice (defined in " . PathCompressor::getPath($definedVals['v'][$matches[0]]['p']) . ":"  . $definedVals['v'][$matches[0]]['l'] .  " and in $p:$l)\n", 0);
										}
										$definedVals['v'][$matches[0]] = array('p' => PathCompressor::getId($p), 'l' => $l, 'v' => '');
									}
									else {
										if(isset($definedVals['v'][$matches[1]])) {
											$this->say("\t\tERROR: Value \"" . $matches[1] . "\" has been defined twice (defined in " . PathCompressor::getPath($definedVals['v'][$matches[1]]['p']) . ":"  . $definedVals['v'][$matches[1]]['l'] .  " and in $p:$l)\n", 0);
										}
										$definedVals['v'][$matches[1]] = array('p' => PathCompressor::getId($p), 'l' => $l, 'v' => trim($matches[2]));
									}
								}
							}
						}
						else {
							if(preg_match('/^define\s+(\S+)\s*\{$/i', $line, $matches)) {
								$isInDefine = true;
								$definedObject = strtolower($matches[1]);
								$definedVals = array('p' => PathCompressor::getId($p), 'l' => $l, 'v' => array());
								//$this->say("Define:        $definedObject\n", 3);
							}
						}
					}
					if($isInDefine) {
						$this->say("\t\tERROR: a define has not been closed\n", 0);
					}
					fclose($fp);
				}
				else {
					$this->say("\t\tERROR: cannot open file: " . $p . "\n", 0);
				}
			}
		}
		return $cfg;
	}
}

class ConsoleWriter {
	protected $verbosity;
	protected $useColors;
	protected static $tty = null;
	protected $supportedColors = array(
		'highlight' => '1',
		'black' => '0;30',
		'dark_gray' => '1;30',
		'darkgray' => '1;30',
		'blue' => '0;34',
		'light_blue' => '1;34',
		'lightblue' => '1;34',
		'green' => '0;32',
		'light_green' => '1;32',
		'lightgreen' => '1;32',
		'cyan' => '0;36',
		'light_cyan' => '1;36',
		'red' => '0;31',
		'light_red' => '1;31',
		'lightred' => '1;31',
		'purple' => '0;35',
		'light_purple' => '1;35',
		'lightpurple' => '1;35',
		'brown' => '0;33',
		'yellow' => '1;33',
		'light_gray' => '0;37',
		'lightgray' => '0;37',
		'white' => '1;37',
		'reset' => '0',
		'none' => '0'
	);

	public function __construct($verbosity, $useColors = null) {
		if($useColors === null) {
			$useColors = self::isTty();
		}
		$this->useColors = (bool)$useColors;
		$this->verbosity = (int)$verbosity;
	}

	public function addCustomColor($name, $code) {
		if(!isset($this->supportedColors[$name])) {
			$this->supportedColors[$name] = $code;
			return true;
		}
		return false;
	}

	public function setColor($color='reset') {
		if($this->useColors) {
			$color = strtolower($color);
			if(isset($this->supportedColors[$color])) {
				echo "\033[" . $this->supportedColors[$color] . "m";
			}
		}
		return $this;
	}

	public function write($str, $level=0, $color=null, $underline=false) {
		if($this->verbosity >= $level) {
		//echo "\033[" . $c . "m" . $str . "\033[0m";
			if($color === null || !$this->useColors) {
				echo $str;
				return $this;
			}
			$this->setColor($color);
			if($underline) echo "\033[4m";
			echo $str . "\033[0m";
		}
		return $this;
	}
	public function writeln($str, $level=0, $color=null) {
		return $this->write("$str\n", $level, $color);
	}

	public static function isTty() {
		if(self::$tty === null) {
			self::$tty = true;
			if (function_exists('posix_isatty')
			    && !posix_isatty(STDOUT)
			) {
			    self::$tty = false;
			}
		}
		return self::$tty;
	}

}

class CfgDiff {
	protected $writer;
	protected $cfg1;
	protected $cfg2;

	public function __construct(Cfg $cfg1, Cfg $cfg2, $useColors = null) {
		if($cfg1 === null) {
			throw new \DomainException('Null is not supported for cfg1.');
		}
		if($cfg2 === null) {
			throw new \DomainException('Null is not supported for cfg2.');
		}
		$this->cfg1 = $cfg1;
		$this->cfg2 = $cfg2;
		$this->writer = new ConsoleWriter(3, $useColors);
	}

	protected function coloredEcho($str, $color) {
		$this->writer->write($str, 0, $color);
	}

	public function display($showStats = true, $showDiff = true) {
		$showStats = (bool)$showStats;
		$showDiff = (bool)$showDiff;
		// nothing to do?
		if($showStats == false && $showDiff == false) return;
		$stats = array(
			'c' => array(
				'New Objects' => 0,
				'Changed Objects' => 0,
				'Removed Objects' => 0,
				'New Values' => 0,
				'Changed Values' => 0,
				'Removed Values' => 0,
			)
		);
		$cfg1 = $this->cfg1->getParsedObjects();
		$cfg2 = $this->cfg2->getParsedObjects();
		// find changed & old nodes
		foreach($cfg1 as $definedObject => $a) {
			if(!isset($cfg2[$definedObject])) {
				foreach($a as $k => $definedVals) {
					$stats['c']['Removed Objects']++;
					if($showDiff) {
						echo "Removed $definedObject: $k\n";
						$this->coloredEcho("<<< ", 'red'); $this->coloredEcho(PathCompressor::getPath($definedVals['p']) . ':' . $definedVals['l'] . "\n", 'cyan');
						$this->coloredEcho("< define $definedObject {\n", 'red');
					}
					foreach($definedVals['v'] as $key => $val) {
						$stats['c']['Removed Values']++;
						if($showDiff) $this->coloredEcho("< \t$key " . $val['v'] . "\n", 'red');
					}
					if($showDiff) $this->coloredEcho("< }\n", 'red');
				}
				continue;
			}
			foreach($a as $k => $definedVals) {
				if(!isset($cfg2[$definedObject][$k])) {
					$stats['c']['Removed Objects']++;
					if($showDiff) {
						echo "Removed $definedObject: $k\n";
						$this->coloredEcho("<<< ", 'red'); $this->coloredEcho(PathCompressor::getPath($definedVals['p']) . ':' . $definedVals['l'] . "\n", 'cyan');
						$this->coloredEcho("< define $definedObject {\n", 'red');
					}
					foreach($definedVals['v'] as $key => $val) {
						$stats['c']['Removed Values']++;
						if($showDiff) $this->coloredEcho("< \t$key " . $val['v'] . "\n", 'red');
					}
					if($showDiff) $this->coloredEcho("< }\n", 'red');
					continue;
				}
				$hasChanges = false;
				foreach($definedVals['v'] as $key => $val) {
					if(!isset($cfg2[$definedObject][$k]['v'][$key]) || $val['v'] != $cfg2[$definedObject][$k]['v'][$key]['v']) {
						$hasChanges = true;
						break;
					}
				}
				foreach($cfg2[$definedObject][$k]['v'] as $key => $val) {
					if(!isset($definedVals['v'][$key])) {
						$hasChanges = true;
						break;
					}
				}
				if($hasChanges) {
					$stats['c']['Changed Objects']++;
					if($showDiff) {
						echo "Changed $definedObject: $k\n";
						$this->coloredEcho("<<< ", 'red'); $this->coloredEcho(PathCompressor::getPath($definedVals['p']) . ':' . $definedVals['l'] . "\n", 'cyan');
						$this->coloredEcho(">>> ", 'green'); $this->coloredEcho(PathCompressor::getPath($cfg2[$definedObject][$k]['p']) . ':' . $cfg2[$definedObject][$k]['l'] . "\n", 'cyan');
						$this->coloredEcho("| define $definedObject {\n", 'brown');
					}
					foreach($definedVals['v'] as $key => $val) {
						if(!isset($cfg2[$definedObject][$k]['v'][$key])) {
							$stats['c']['Removed Values']++;
							if($showDiff) $this->coloredEcho("< \t$key " . $val['v'] . "\n", 'red');
						}
						elseif($val['v'] != $cfg2[$definedObject][$k]['v'][$key]['v']) {
							$stats['c']['Changed Values']++;
							if($showDiff) {
								$this->coloredEcho("< \t$key " . $val['v'] . "\n", 'red');
								$this->coloredEcho("> \t$key " . $cfg2[$definedObject][$k]['v'][$key]['v'] . "\n", 'green');
							}
						}
						else {
							if($showDiff) $this->coloredEcho("| \t$key " . $val['v'] . "\n", 'brown');
						}
					}
					foreach($cfg2[$definedObject][$k]['v'] as $key => $val) {
						if(!isset($definedVals['v'][$key])) {
							$stats['c']['New Values']++;
							if($showDiff) $this->coloredEcho("> \t$key " . $val['v'] . "\n", 'green');
						}
					}
					if($showDiff) $this->coloredEcho("| }\n", 'brown');
				}
			}
		}

		// new nodes
		foreach($cfg2 as $definedObject => $a) {
			if(!isset($cfg1[$definedObject])) {
				foreach($a as $k => $definedVals) {
					$stats['c']['New Objects']++;
					if($showDiff) {
						echo "New $definedObject: $k\n";
						$this->coloredEcho(">>> ", 'green'); $this->coloredEcho(PathCompressor::getPath($definedVals['p']) . ':' . $definedVals['l'] . "\n", 'cyan');
						$this->coloredEcho("> define $definedObject {\n", 'green');
					}
					foreach($definedVals['v'] as $key => $val) {
						$stats['c']['New Values']++;
						if($showDiff) $this->coloredEcho("> \t$key " . $val['v'] . "\n", 'green');
					}
					if($showDiff) $this->coloredEcho("> }\n", 'green');
				}
				continue;
			}
			foreach($a as $k => $definedVals) {
				if(!isset($cfg1[$definedObject][$k])) {
					$stats['c']['New Objects']++;
					if($showDiff) {
						echo "New $definedObject: $k\n";
						$this->coloredEcho(">>> ", 'green'); $this->coloredEcho(PathCompressor::getPath($definedVals['p']) . ':' . $definedVals['l'] . "\n", 'cyan');
						$this->coloredEcho("> define $definedObject {\n", 'green');
					}
					foreach($definedVals['v'] as $key => $val) {
						$stats['c']['New Values']++;
						if($showDiff) $this->coloredEcho("> \t$key " . $val['v'] . "\n", 'green');
					}
					if($showDiff) $this->coloredEcho("> }\n", 'green');
					continue;
				}
			}
		}
		if($showStats) {
			if($showDiff) echo "\n";
			echo "Statistics:\n";
			foreach($stats['c'] as $k => $v) {
				echo "\t" . sprintf('%16s: %s', $k, $v) . "\n";
				
			}
		}
	}
}
